title: CerbiSuite
description: Unified Logging, Governance, and Observability
url: "https://zeroshi.github.io/CerbiSite"
theme: minimal-mistakes-jekyll
paginate: 10
paginate_path: "/page:num/"
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
markdown: kramdown

